In [40]:
import requests
import datetime, time, logging, os, traceback
import pandas as pd
from numpy import nan
from functions import functions
import json

from urllib.parse import quote_plus
from sqlalchemy import create_engine
engine = create_engine('postgresql://zbrothers:%s@localhost:5434/zbrothers' % quote_plus('zbrothers@2026'))

In [2]:
API_TOKEN = os.environ['OLIST_API_TOKEN']

today = datetime.date.today()
# today = datetime.datetime(2026, 4, 15)
today_str = today.strftime('%d/%m/%Y')

situacao_dict = {
    'aguardando_separacao': 1,
    'em_separacao': 4,
    'separada': 2,
    'embalada': 3
}

In [3]:
def getAllProductsPicking(situacao_dict: dict, today_str: str) -> pd.DataFrame:
    df_list = []
    for situacao, situacao_id in situacao_dict.items():
        print(f'Getting data for situacao: {situacao} (id: {situacao_id})')
        df = functions.getInfosPesquisar(
            url='https://api.tiny.com.br/api2/separacao.pesquisa.php',
            params={
                'token': API_TOKEN,
                'dataInicial': today_str,
                'situacao': situacao_id
            }
        )
        df['situacao'] = situacao
        df_list.append(df)
    return pd.concat(df_list, ignore_index=True)

In [4]:
df_all_products_picking = getAllProductsPicking(situacao_dict, today_str)

Getting data for situacao: aguardando_separacao (id: 1)

In [5]:
df_all_products_picking_detail = functions.getInfosObter('https://api.tiny.com.br/api2/separacao.obter.php', 
                                                         {'token': API_TOKEN, 'formato': 'json', 'idSeparacao': None},
                                                         df_all_products_picking['id'].tolist(),
                                                         'idSeparacao')

{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559156', 'idOrigem': '1075555738', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1069373421', 'descricao': 'LPL-750 LIXADEIRA PAREDE LED LYNUS 750W 127V', 'codigo': '000114707', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188765', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016170316478', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485118', 'destinatario': 'Carlos Alberto Dos Santos Junior', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559106', 'idOrigem': '1075555864', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1074237446', 'descricao': 'MACHO MANUAL AR  8X1,00MB JG 2PC VONDER', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'JG', 'localizacao': 'Z051', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188787', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016161940106', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484299', 'destinatario': 'Thiago Oliveira Mendes', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559056', 'idOrigem': '1075555884', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1073833968', 'descricao': 'DISCO LIXA 180MM G 60 C/10 VONDER', 'codigo': '', 'quantidade': '6.0000', 'unidade': 'CJ', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188791', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012707737095', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485233', 'destinatario': 'Marco Aurelio Magnago Alves', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559052', 'idOrigem': '1075556002', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1074604027', 'descricao': 'SACA TERMINAL BATERIAS C/2 GARRAS VONDER', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'E4500', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188809', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016171941130', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031362137', 'destinatario': 'Washington Junior Matos Silva', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559035', 'idOrigem': '1075556077', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1069373658', 'descricao': 'Bolsa Lona BFL-40 Para Ferramentas Resistente Lynus', 'codigo': '00000219.0', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': 'AL0108', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188828', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016163675858', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484453', 'destinatario': 'Salvador Peluso Basile Neto', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559016', 'idOrigem': '1075556179', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1057052051', 'descricao': 'MACACO JACARE PORTATIL 2T MALETA VONDER', 'codigo': '6874200200', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188840', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012708730789', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485409', 'destinatario': 'Mauro Yukiyoshi Hamada', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559001', 'idOrigem': '1075556201', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1069372898', 'descricao': 'Cortador De Chapa De Aço Para Parafusadeira Sccl-2 Lynus', 'codigo': '00001058.0', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': 'A1001', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188842', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016164533212', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484534', 'destinatario': 'Jhulyan Alves Dos Santos', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558987', 'idOrigem': '1075556273', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1057725710', 'descricao': 'CH ALLEN JG 2,0A10MM 42-88M C/SUP GEDORE', 'codigo': '', 'quantidade': '2.0000', 'unidade': 'JG', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188857', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012704142659', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484934', 'destinatario': 'EQ TECH EQUIPAMENTOS LTDA', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558983', 'idOrigem': '1075556309', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075351658', 'descricao': 'KIT ESPATULAS ESFERICAS PARA ACABAMENTO', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'E4506', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188860', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012704232321', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484940', 'destinatario': 'Larissa Reis Nascimento', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558979', 'idOrigem': '1075556324', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1066419229', 'descricao': 'MAQUINA INVERSORA DE SOLDA EASY 120 MMA 220V BALMER', 'codigo': '30079564', 'quantidade': '1.0000', 'unidade': 'pc', 'localizacao': 'A0301', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188863', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012704216363', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484941', 'destinatario': 'MAURICIO CAVALCANTI', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558970', 'idOrigem': '1075556330', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1074604027', 'descricao': 'SACA TERMINAL BATERIAS C/2 GARRAS VONDER', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'E4500', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188864', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012700794815', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484571', 'destinatario': 'Aurelia Fanti', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558966', 'idOrigem': '1075556332', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075558319', 'descricao': 'MASCARA DE SOLDA - TRIPLA REGULAGEM - CR2 - TON 4-9/13 - C.A. 49183 - V8 BRASIL', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188865', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016168351716', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484948', 'destinatario': 'Diueise Celestrino Bettio', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558961', 'idOrigem': '1075556450', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1073833968', 'descricao': 'DISCO LIXA 180MM G 60 C/10 VONDER', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'CJ', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188885', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016173923374', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485544', 'destinatario': 'Ediel Silva Rocha', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558957', 'idOrigem': '1075556563', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075316582', 'descricao': 'REGULADOR DE PRESSAO ARGONIO - V8 BRASIL', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188902', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016166128946', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484673', 'destinatario': 'Marcos Moreira', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558910', 'idOrigem': '1075556772', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1067944872', 'descricao': 'Catraca Reversível 1/2" Vonder Cabo Emborrachado', 'codigo': '3059120000', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'E4001', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188932', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016158380438', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031483826', 'destinatario': 'Wagner Alexandre Dos Santos', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558852', 'idOrigem': '1075556816', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075550234', 'descricao': 'Talha de Corrente MTC 5,0T-5m', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188941', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016144372190', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031482444', 'destinatario': 'Felipe Goncalves Diniz', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558847', 'idOrigem': '1075557148', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1057052107', 'descricao': 'MAQ CORTAR GRAMA C/RECOL MGV1001 220V VD', 'codigo': '6806101220', 'quantidade': '1.0000', 'unidade': 'UN', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '188990', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016129278628', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484840', 'destinatario': 'DIVISA VEICULOS LTDA', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558831', 'idOrigem': '1075557382', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1074491124', 'descricao': 'ABAFADOR DE RUIDOS CONCHA ARV200 VONDER', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189025', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2604280Q8FWMD3', 'idFormaEnvio': '737931940', 'formaEnvio': 'Shopee Envios', 'idContato': '1031485077', 'destinatario': 'Derick rodigo Da Silva', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558818', 'idOrigem': '1075557497', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '847488742', 'descricao': 'FIO DE NYLON ROÇADEIRA APARADOR GRAMA 1,8mm X 15 mt Vonder', 'codigo': '3373180015', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'E1601  /// E1602', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189044', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2604280W3PV4R6', 'idFormaEnvio': '737931940', 'formaEnvio': 'Shopee Envios', 'idContato': '1031485210', 'destinatario': 'Renato Da Conceição Silva', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558791', 'idOrigem': '1075557596', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1060783345', 'descricao': 'FITA ANTIDERRAP 50MMX15M PRETA 954', 'codigo': '1022005150', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'C0702', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189059', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '26042702W87192', 'idFormaEnvio': '737931940', 'formaEnvio': 'Shopee Envios', 'idContato': '1031484479', 'destinatario': 'Eduardo Gesualdo', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075558744', 'idOrigem': '1075557784', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1074491124', 'descricao': 'ABAFADOR DE RUIDOS CONCHA ARV200 VONDER', 'codigo': '', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189089', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '26042815USFAET', 'idFormaEnvio': '737931940', 'formaEnvio': 'Shopee Envios', 'idContato': '1031485539', 'destinatario': 'Gabriela Feitosa', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559407', 'idOrigem': '1075559399', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075286567', 'descricao': 'MASCARA DE SOLDA - TRIPLA REGULAGEM - 8K - TON 4-5/9-9/13 - C.A. 49697 - V8 BRASIL', 'codigo': '1003494', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189137', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016176216586', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485699', 'destinatario': 'Erick Boesing', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559429', 'idOrigem': '1075559408', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1072163690', 'descricao': 'Raspador Plano Para Tintas Piso Vidro Cerâmica Com 10 Lâminas Rp011 Vonder', 'codigo': '3599011000', 'quantidade': '1.0000', 'unidade': 'Un', 'localizacao': 'E3501 /// E3502', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189138', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016176354840', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031484765', 'destinatario': 'Andre Luis Guimaraes Cordeiro', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559442', 'idOrigem': '1075559437', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075232559', 'descricao': 'DISCO CORTE 114,3X1,0X22,2 STA8061 STANL', 'codigo': '1240114100', 'quantidade': '100.0000', 'unidade': 'PC', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189139', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012712847043', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485722', 'destinatario': '59.542.512 SEBASTIAO MANOEL ROCHA', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559454', 'idOrigem': '1075559449', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1070961100', 'descricao': 'Bomba Recarregável Para Galão De Água Vonder', 'codigo': '8599070004', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'E4105', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189140', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016176559492', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485773', 'destinatario': 'HENRIQUE B', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559475', 'idOrigem': '1075559455', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1070642500', 'descricao': 'RASPADOR DE SELANTE JG 6PCS VONDER', 'codigo': '3599003001', 'quantidade': '1.0000', 'unidade': 'JG', 'localizacao': 'E1600', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189141', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016176589916', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485782', 'destinatario': 'Andre Spinosa Ticona', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559481', 'idOrigem': '1075559463', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1075559059', 'descricao': 'ESTRELA PARA REPUXO 2MM - CAIXA COM 10 UN', 'codigo': '87567', 'quantidade': '1.0000', 'unidade': 'CX', 'localizacao': '', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189142', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000016176630174', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485783', 'destinatario': 'Luiz Carlos Viegas', 'situacaoOrigem': None}}}
{'retorno': {'status_processamento': '3', 'status': 'OK', 'separacao': {'id': '1075559543', 'idOrigem': '1075559533', 'objOrigem': 'notafiscal', 'situacao': '1', 'situacaoCheckout': '1', 'dataCriacao': '28/04/2026', 'itens': [{'idProduto': '1060336374', 'descricao': 'Serra Circular A Bateria ISCV1831 Vonder', 'codigo': '6004183100', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'D0503', 'infoAdicional': ''}, {'idProduto': '909357521', 'descricao': 'BATERIA LINHA INTERCAMBIAVEL 18V 2.0AH IBV1802 VONDER', 'codigo': '6004180200', 'quantidade': '2.0000', 'unidade': 'PC', 'localizacao': 'D0102', 'infoAdicional': ''}, {'idProduto': '909357547', 'descricao': 'CARREGADOR DE BATERIA 18V ICBV1805 VONDER', 'codigo': '6004180500', 'quantidade': '1.0000', 'unidade': 'PC', 'localizacao': 'D0202', 'infoAdicional': ''}], 'qtdVolumes': '0', 'numero': '189143', 'dataEmissao': '28/04/2026', 'numeroPedidoEcommerce': '2000012713075021', 'idFormaEnvio': '675234044', 'formaEnvio': 'Mercado Envios', 'idContato': '1031485814', 'destinatario': 'Ilvando Luiz Mota', 'situacaoOrigem': None}}}

In [18]:
df_all_products_picking

,id,idOrigem,objOrigem,situacao,dataCriacao,dataSeparacao,dataCheckout,destinatario,idContato,numero,dataEmissao,idFormaEnvio,numeroPedidoEcommerce,idOrigemVinc,objOrigemVinc,situacaoVenda
0,1075559156,1075555738,notafiscal,aguardando_separacao,28/04/2026,None,None,Carlos Alberto Dos Santos Junior,1031485118,188765,28/04/2026,675234044,2000016170316478,1075551978,venda,6
1,1075559106,1075555864,notafiscal,aguardando_separacao,28/04/2026,None,None,Thiago Oliveira Mendes,1031484299,188787,28/04/2026,675234044,2000016161940106,1075543391,venda,6
2,1075559056,1075555884,notafiscal,aguardando_separacao,28/04/2026,None,None,Marco Aurelio Magnago Alves,1031485233,188791,28/04/2026,675234044,2000012707737095,1075552809,venda,6
3,1075559052,1075556002,notafiscal,aguardando_separacao,28/04/2026,None,None,Washington Junior Matos Silva,1031362137,188809,28/04/2026,675234044,2000016171941130,1075552990,venda,6
4,1075559035,1075556077,notafiscal,aguardando_separacao,28/04/2026,None,None,Salvador Peluso Basile Neto,1031484453,188828,28/04/2026,675234044,2000016163675858,1075545064,venda,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,1075558086,1075558063,notafiscal,embalada,28/04/2026,28/04/2026,28/04/2026,Lindiney Pereira Dias,1031485469,189132,28/04/2026,737931940,26042812JVJFDC,1075553773,venda,6
403,1075558085,1075558072,notafiscal,embalada,28/04/2026,28/04/2026,28/04/2026,Sayonara Helman Palitot,1031485475,189133,28/04/2026,737931940,26042812RQF03C,1075553846,venda,6
404,1075558100,1075558078,notafiscal,embalada,28/04/2026,28/04/2026,28/04/2026,Wdson Fraga,1031485508,189134,28/04/2026,737931940,26042814AMU8XE,1075554223,venda,6
405,1075558098,1075558087,notafiscal,embalada,28/04/2026,28/04/2026,28/04/2026,Carla Xavier da Costa,1031485510,189135,28/04/2026,737931940,26042814F7RV1Y,1075554237,venda,6
406,1075558104,1075558089,notafiscal,embalada,28/04/2026,28/04/2026,28/04/2026,Erbio Rosa Ferreira,1031485532,189136,28/04/2026,737931940,26042815GVDVHY,1075554327,venda,6

In [21]:
df_all_products_picking_merged = df_all_products_picking_detail.merge(df_all_products_picking, on='id', how='left', validate='1:1')#.drop(columns=['id_y']).rename(columns={'id_x': 'id'})

In [23]:
df_all_products_picking_merged.columns

Index(['id', 'idOrigem_x', 'objOrigem_x', 'situacao_x', 'situacaoCheckout',
       'dataCriacao_x', 'itens', 'qtdVolumes', 'numero_x', 'dataEmissao_x',
       'numeroPedidoEcommerce_x', 'idFormaEnvio_x', 'formaEnvio',
       'idContato_x', 'destinatario_x', 'situacaoOrigem', 'dataSeparacao_x',
       'idUsuarioEmbalador', 'dataCheckout_x', 'idOrigem_y', 'objOrigem_y',
       'situacao_y', 'dataCriacao_y', 'dataSeparacao_y', 'dataCheckout_y',
       'destinatario_y', 'idContato_y', 'numero_y', 'dataEmissao_y',
       'idFormaEnvio_y', 'numeroPedidoEcommerce_y', 'idOrigemVinc',
       'objOrigemVinc', 'situacaoVenda'],
      dtype='str')

In [24]:
df_all_products_picking_columns = df_all_products_picking_merged[['id', 'idOrigem_x', 'objOrigem_x', 'situacao_x', 'situacaoCheckout',
       'dataCriacao_x', 'itens', 'qtdVolumes', 'numero_x', 'dataEmissao_x',
       'numeroPedidoEcommerce_x', 'idFormaEnvio_x', 'formaEnvio',
       'idContato_x', 'destinatario_x', 'situacaoOrigem', 'dataSeparacao_x',
       'idUsuarioEmbalador', 'dataCheckout_x', 'idOrigemVinc',
       'objOrigemVinc', 'situacaoVenda']]

In [68]:
df_all_products_picking_rename = df_all_products_picking_columns.rename(columns={x: x.replace('_x', '') for x in df_all_products_picking_columns.columns})\
    .rename(columns={'idUsuarioEmbalador': 'picking_operator_id'})

df_all_products_picking_rename["itens"] = df_all_products_picking_rename["itens"].apply(
    lambda x: json.dumps(x, ensure_ascii=False) if x is not None else None
)

df_all_products_picking_rename[['dataCriacao', 'dataEmissao', 'dataSeparacao', 'dataCheckout']] = df_all_products_picking_rename[['dataCriacao', 'dataEmissao', 'dataSeparacao', 'dataCheckout']].apply(lambda x: pd.to_datetime(x, format='%d/%m/%Y'))

In [73]:
embaladores_unicos = df_all_products_picking_rename[['picking_operator_id']].drop_duplicates().dropna()

In [74]:
embaladores_unicos.rename(columns={'picking_operator_id': 'id'})

             id
132  1240202884
154   879165082
307  1084497214

In [75]:
embaladores_unicos.rename(columns={'picking_operator_id': 'id'}).to_sql("picking_operators", engine, if_exists='append', index=False)

3

In [82]:
pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2026.3.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: pandas>=1.5.0 in /home/gustavo/zbrothers/.venv/lib/python3.13/site-packages (from fastparquet) (3.0.2)
Requirement already satisfied: numpy in /home/gustavo/zbrothers/.venv/lib/python3.13/site-packages (from fastparquet) (2.4.4)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.11.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in /home/gustavo/zbrothers/.venv/lib/python3.13/site-packages (from fastparquet) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/gustavo/zbrothers/.venv/lib/python3.13/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/gustavo/zbrothers/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.3.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 27.1 MB/s  0:00:00
Downloading cramjam-2.11.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 53.1 MB/s  0:00:00
Downloading fsspec-2026.3.0-py3-none-any.whl (202 kB)
Installing collected packages: fsspec, cramjam, fastparquet
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [fastparquet] [fastparquet]
Successfully installed cramjam-2.11.0 fastparquet-2026.3.0 fsspec-2026.3.0
Note: you may need to restart the kernel to use updated packages.

In [83]:
df_all_products_picking_rename.to_parquet('df_all_products_picking_rename.parquet', index=False)

In [84]:
df = pd.read_parquet('df_all_products_picking_rename.parquet')

In [76]:
df_all_products_picking_rename.to_sql('product_picking', engine, if_exists='append', index=False)

407